all: print-zero-sums find-sum-pair trapped-water

trapped-water: trapped-water.cpp
	g++ -std=c++11 $< -o $@

print-zero-sums: print-zero-sums.cpp
	g++ -std=c++11 $< -o $@

find-sum-pair: find-sum-pair.cpp
	g++ -std=c++11 $< -o $@

clean:
	rm -rf print-zero-sums find-sum-pair

